// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkjourmhjgrbgyqwzwzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ram91cm1oamdyYmd5cXd6d3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTM1MzAsImV4cCI6MjA3MjQ4OTUzMH0.XsiA4A8C97lY_GSP5qNAwKlEU4BDr6F62j58Mj9KKOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});